---
.travis.yml:
  acceptance:
    - '*'
  forge_password: "QlLAT3W2KlpYldcAiGHW/1ABoqimNtSP01ELj8jRMY9tKde9eDyUXUkEmCsjC2FPSP8amV04tIbInpMrzHhsqXl76hK5n0RWVgV93tbbxltKvmWdzfM18UeJxOO6psUfkLgydYDtgbo12IXQbtnm5gNXiYGPnKghwOwfv+XaW98="
  allow_failures:
    - rvm: default
      env: BEAKER_set="debian-6"
    - rvm: default
      env: BEAKER_set="debian-7"
    - rvm: default
      env: BEAKER_set="centos-5"
    - rvm: default
      env: BEAKER_set="centos-6"
    - rvm: default
      env: BEAKER_set="centos-7"
